
package org.exemple.model;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Salutation", targetNamespace = "http://model.exemple.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Salutation {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bonjour", targetNamespace = "http://model.exemple.org/", className = "org.exemple.model.Bonjour")
    @ResponseWrapper(localName = "bonjourResponse", targetNamespace = "http://model.exemple.org/", className = "org.exemple.model.BonjourResponse")
    @Action(input = "http://model.exemple.org/Salutation/bonjourRequest", output = "http://model.exemple.org/Salutation/bonjourResponse")
    public String bonjour();

    /**
     * 
     * @return
     *     returns java.util.List<org.exemple.model.Utilisateur>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://model.exemple.org/", className = "org.exemple.model.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://model.exemple.org/", className = "org.exemple.model.GetAllUserResponse")
    @Action(input = "http://model.exemple.org/Salutation/getAllUserRequest", output = "http://model.exemple.org/Salutation/getAllUserResponse")
    public List<Utilisateur> getAllUser();

}
