
package org.exemple;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalutationsService", targetNamespace = "http://exemple.org/", wsdlLocation = "http://10.138.2.13:8080/ProjetJavaEE/ws/salut?wsdl")
public class SalutationsService
    extends Service
{

    private final static URL SALUTATIONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALUTATIONSSERVICE_EXCEPTION;
    private final static QName SALUTATIONSSERVICE_QNAME = new QName("http://exemple.org/", "SalutationsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.138.2.13:8080/ProjetJavaEE/ws/salut?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALUTATIONSSERVICE_WSDL_LOCATION = url;
        SALUTATIONSSERVICE_EXCEPTION = e;
    }

    public SalutationsService() {
        super(__getWsdlLocation(), SALUTATIONSSERVICE_QNAME);
    }

    public SalutationsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALUTATIONSSERVICE_QNAME, features);
    }

    public SalutationsService(URL wsdlLocation) {
        super(wsdlLocation, SALUTATIONSSERVICE_QNAME);
    }

    public SalutationsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALUTATIONSSERVICE_QNAME, features);
    }

    public SalutationsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalutationsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Salutations
     */
    @WebEndpoint(name = "SalutationsPort")
    public Salutations getSalutationsPort() {
        return super.getPort(new QName("http://exemple.org/", "SalutationsPort"), Salutations.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Salutations
     */
    @WebEndpoint(name = "SalutationsPort")
    public Salutations getSalutationsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://exemple.org/", "SalutationsPort"), Salutations.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALUTATIONSSERVICE_EXCEPTION!= null) {
            throw SALUTATIONSSERVICE_EXCEPTION;
        }
        return SALUTATIONSSERVICE_WSDL_LOCATION;
    }

}
