
package com.m2i.formation.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Welcome", targetNamespace = "http://ws.formation.m2i.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Welcome {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessStart", targetNamespace = "http://ws.formation.m2i.com/", className = "com.m2i.formation.ws.GetMessStart")
    @ResponseWrapper(localName = "getMessStartResponse", targetNamespace = "http://ws.formation.m2i.com/", className = "com.m2i.formation.ws.GetMessStartResponse")
    @Action(input = "http://ws.formation.m2i.com/Welcome/getMessStartRequest", output = "http://ws.formation.m2i.com/Welcome/getMessStartResponse")
    public String getMessStart();

}
